# Generated by Django 4.2.2 on 2024-03-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciepe_name', models.TextField(max_length=100)),
                ('procedure', models.TextField()),
                ('img', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
